# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

[line_break]
disabled = true

[time]
disabled = true

# Inserts a blank line between shell prompts
add_newline = false

# Replace the "❯" symbol in the prompt with "➜"
[character] # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)" # The "success_symbol" segment is being set to "➜" with the color "bold green"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[aws]
disabled = true

[azure]
disabled = true

[gcloud]
disabled = true

[git_status]
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"

[nodejs]
disabled = true

[rust]
disabled = true

[lua]
disabled = true

[cmd_duration]
disabled = true
